ansible-playbook main.yml -e "provider=gce
                                server_name=algo_ansible_part_deux
                                ondemand_cellular=false
                                ondemand_wifi=false
                                local_dns=true
                                ssh_tunneling=false
                                windows=false
                                store_cakey=false
                                region=us-east1-b
                                do_token=token
				gce_credentials_file=./bwap_secret/package.json"
